import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const nav = [['Home','home'],['About','about'],['Services','services'],['Industries','industries'],['How It Works','process'],['Compliance','compliance'],['Contact','contact']]

const Icon = ({name}) => {
  const paths = {
    target:'M12 2a10 10 0 1 0 10 10M12 6a6 6 0 1 0 6 6M12 10a2 2 0 1 0 2 2M22 2l-6 6M17 2h5v5',
    people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',
    shield:'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10M9 12l2 2 4-4',
    chart:'M3 3v18h18M7 16l4-5 4 3 5-7',
    check:'M20 6 9 17l-5-5',
    clock:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20M12 6v6l4 2',
    globe:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20M2 12h20M12 2c3 3 3 17 0 20M12 2c-3 3-3 17 0 20',
    mail:'M4 4h16v16H4zM4 6l8 7 8-7',
    phone:'M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.8a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.28-1.28a2 2 0 0 1 2.11-.45c.9.34 1.84.57 2.8.7A2 2 0 0 1 22 16.92z',
    pin:'M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0M12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6'
  }
  return <svg aria-hidden="true" viewBox="0 0 24 24"><path d={paths[name]}/></svg>
}

function Header(){
  const [open,setOpen]=useState(false)
  return <header className="header"><div className="container nav-wrap">
    <a className="brand" href="#home" aria-label="SKAPS HR Solutions home"><span className="brand-mark">S</span><span>SKAPS <b>HR Solutions</b></span></a>
    <button className="menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><span/><span/><span/></button>
    <nav className={open?'nav open':'nav'} aria-label="Main navigation">{nav.map(([label,id])=><a key={id} onClick={()=>setOpen(false)} href={`#${id}`}>{label}</a>)}<a className="btn small" href="#contact" onClick={()=>setOpen(false)}>Schedule Consultation</a></nav>
  </div></header>
}

const SectionTitle=({eyebrow,title,copy})=><div className="section-title reveal">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{copy&&<p>{copy}</p>}</div>
const Metric=({icon,title,text})=><div className="metric"><span className="icon"><Icon name={icon}/></span><div><small>{title}</small><strong>{text}</strong></div></div>

function Hero(){return <section id="home" className="hero"><div className="container hero-grid">
  <div className="hero-copy reveal"><span className="eyebrow">Trusted workforce partner</span><h1>Building High<br/>Performing Teams for<br/><em>Modern Businesses</em></h1><p>SKAPS HR Solutions is a comprehensive workforce and recruitment solutions provider helping organizations streamline hiring, payroll, compliance, and workforce operations.</p><div className="actions"><a className="btn" href="#contact">Schedule Consultation <span>→</span></a><a className="btn secondary" href="#services">Explore Services</a></div></div>
  <div className="hero-visual reveal" aria-label="Workforce operations dashboard illustration"><div className="orb one"/><div className="orb two"/><div className="dashboard"><div className="dash-top"><span/><span/><span/></div><div className="dash-body"><div className="chart-bars">{[45,72,55,88,67,95,78].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="dash-list"><b/><b/><b/></div></div></div><div className="float f1"><Icon name="check"/><span>Payroll Management<strong>100% Accurate</strong></span></div><div className="float f2"><Icon name="people"/><span>Workforce Expansion<strong>24+ New Hires</strong></span></div><div className="float f3"><Icon name="shield"/><span>Compliance Status<strong>Verified</strong></span></div></div>
  </div></section>}

const services=[['Talent Acquisition','End-to-end hiring solutions that connect your business with qualified, role-ready professionals.','people'],['Payroll Management','Accurate, timely payroll administration designed for growing and distributed teams.','chart'],['Compliance & Statutory','Reliable support for workforce regulations, documentation and statutory requirements.','shield'],['Contract Staffing','Scale teams quickly with flexible staffing built around your changing business needs.','clock'],['HR Operations','Streamlined onboarding, employee records and day-to-day workforce administration.','target'],['Global Workforce','Build and support distributed teams with practical operational guidance across markets.','globe']]
const industries=['Technology & IT Services','Healthcare','Manufacturing','Financial Services','Retail & E-commerce','Startups & Growing Businesses']

function App(){
 useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));return()=>io.disconnect()},[])
 return <><Header/><main><Hero/>
 <section className="trust"><div className="container"><p>Trusted by organizations managing <strong>modern and distributed workforces</strong> across multiple industries.</p><div className="logos" aria-label="Client organizations"><span>GYANSYS</span><span>kanerika</span><span>SAFE</span><span>SNOWRELIC</span><span>Squizify</span><span>ivy mobility</span></div></div></section>
 <section id="about" className="about section"><div className="container split"><div className="about-visual reveal"><div className="people-art"><span/><span/><span/><span/></div><div className="experience"><strong>15+</strong><span>Years of collective<br/>industry experience</span></div></div><div className="reveal"><span className="eyebrow">About SKAPS</span><h2>Your People. Our Expertise.<br/><em>Shared Growth.</em></h2><p>We help organizations build reliable teams and simplify complex workforce operations. Our approach brings recruitment, payroll, compliance and employee support together in one dependable partnership.</p><ul className="checks"><li><Icon name="check"/>Solutions shaped around your goals</li><li><Icon name="check"/>Clear, responsive communication</li><li><Icon name="check"/>Processes designed to scale</li></ul><a href="#process" className="text-link">Discover our approach →</a></div></div></section>
 <section id="services" className="section soft"><div className="container"><SectionTitle eyebrow="What we do" title={<>Workforce Solutions Built for <em>Business Momentum</em></>} copy="Practical HR services that help teams move faster, operate confidently and stay focused on growth."/><div className="cards">{services.map(([t,d,i],n)=><article className="card reveal" key={t}><span className="card-num">0{n+1}</span><span className="service-icon"><Icon name={i}/></span><h3>{t}</h3><p>{d}</p><a href="#contact" aria-label={`Discuss ${t}`}>Learn more <span>→</span></a></article>)}</div></div></section>
 <section id="process" className="section process"><div className="container"><SectionTitle eyebrow="How it works" title={<>A Clear Path from Need to <em>Results</em></>} copy="A focused process keeps every engagement transparent, efficient and aligned."/><div className="steps">{[['01','Discover','We understand your goals, gaps and workforce priorities.'],['02','Design','We shape the right hiring and operations solution.'],['03','Deliver','Our team executes with clear milestones and communication.'],['04','Support','We measure, improve and continue supporting your growth.']].map(([n,t,d])=><article className="step reveal" key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
 <section id="compliance" className="section dark"><div className="container compliance-grid"><div className="reveal"><span className="eyebrow">Built on confidence</span><h2>Compliance That Keeps<br/>Your Business <em>Moving</em></h2><p>From accurate payroll to employee documentation, we help reduce operational risk with consistent processes and dependable support.</p><a className="btn light" href="#contact">Talk to a specialist →</a></div><div className="compliance-panel reveal"><div className="shield-big"><Icon name="shield"/></div><div className="status"><span><i/>Payroll accuracy</span><strong>100%</strong></div><div className="status"><span><i/>Documentation readiness</span><strong>Verified</strong></div><div className="status"><span><i/>Operational support</span><strong>Active</strong></div></div></div></section>
 <section id="industries" className="section"><div className="container"><SectionTitle eyebrow="Industries" title={<>Supporting Workforce Growth Across <em>Multiple Industries</em></>} copy="Flexible expertise for organizations at different stages of growth."/><div className="industry-grid">{industries.map((x,i)=><div className="industry reveal" key={x}><span>0{i+1}</span><h3>{x}</h3></div>)}</div><div className="benefits"><h2>The Smart Way to Build a <em>Flexible Workforce</em></h2><div>{[['Workforce flexibility','people'],['Cost efficiency','chart'],['Specialized talent','target'],['Reduced compliance risk','shield']].map(([t,i])=><span key={t}><Icon name={i}/><b>{t}</b></span>)}</div></div></div></section>
 <section className="section global"><div className="container global-grid"><div className="reveal"><span className="eyebrow">Global reach</span><h2>Supporting Organizations Across <em>Global Markets</em></h2><p>Local attention backed by the perspective needed to support modern and distributed teams.</p><div className="region-tags"><span>India</span><span>United States</span><span>Asia Pacific</span></div></div><div className="map reveal" aria-label="Stylized world map"><Icon name="globe"/><i className="pin p1"/><i className="pin p2"/><i className="pin p3"/></div></div></section>
 <Contact/>
 </main><Footer/></>}

const submitLead=async()=>{await new Promise(r=>setTimeout(r,650));return{ok:true}}
function Contact(){const [errors,setErrors]=useState({});const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false)
 const submit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const next={};if(!data.name.trim())next.name='Please enter your name.';if(!data.company.trim())next.company='Please enter your company.';if(!/^\S+@\S+\.\S+$/.test(data.email))next.email='Enter a valid email address.';if(!/^[+\d][\d\s()-]{7,}$/.test(data.phone))next.phone='Enter a valid phone number.';if(data.message.trim().length<10)next.message='Tell us a little more about your requirements.';setErrors(next);if(Object.keys(next).length)return;setBusy(true);await submitLead(data);setBusy(false);setSent(true);e.currentTarget.reset()}
 return <section id="contact" className="section contact"><div className="container contact-grid"><div className="reveal"><span className="eyebrow">Let’s work together</span><h2>Let’s Start the <em>Conversation</em></h2><p>Whether you are streamlining payroll, expanding your workforce, or strengthening compliance operations, our team is ready to support your business.</p><div className="details"><a href="tel:+918500004521"><Icon name="phone"/><span><small>Phone</small>+91 8500004521</span></a><a href="mailto:info@skaps.co.in"><Icon name="mail"/><span><small>Email</small>info@skaps.co.in</span></a><div><Icon name="pin"/><span><small>Office location</small>First Floor, ARD Magnum, Door No: 12-7-134/H/2,<br/>Miyapur, Hyderabad – 500018</span></div></div></div><form className="form reveal" onSubmit={submit} noValidate>{sent&&<div className="success" role="status"><Icon name="check"/><div><strong>Demo request captured</strong><span>This review form does not send or store data yet.</span></div></div>}<div className="form-row"><Field name="name" label="Full name" placeholder="Your name" error={errors.name}/><Field name="company" label="Company name" placeholder="Your organization name" error={errors.company}/></div><div className="form-row"><Field name="email" type="email" label="Email address" placeholder="your@email.com" error={errors.email}/><Field name="phone" type="tel" label="Phone number" placeholder="Best number to reach you" error={errors.phone}/></div><label>How can we help you?<textarea name="message" placeholder="Tell us about your requirements" aria-invalid={!!errors.message}/>{errors.message&&<small className="error">{errors.message}</small>}</label><button className="btn submit" disabled={busy}>{busy?'Capturing request…':'Send Message'} <span>→</span></button><p className="form-note">Demo form — details are validated locally and are not transmitted.</p></form></div></section>}
function Field({name,label,error,...props}){return <label>{label}<input name={name} {...props} aria-invalid={!!error}/>{error&&<small className="error">{error}</small>}</label>}
function Footer(){return <footer><div className="container"><a className="brand footer-brand" href="#home"><span className="brand-mark">S</span><span>SKAPS <b>HR SOLUTIONS</b></span></a><p>Workforce management and recruitment solutions for modern organizations.</p><div className="footer-links">{nav.slice(1).map(([l,id])=><a key={id} href={`#${id}`}>{l}</a>)}</div><div className="copyright">© 2026 SKAPS HR Solutions. All rights reserved.</div></div></footer>}

createRoot(document.getElementById('root')).render(<App/>)
